name: Docs

on:
  push:
    paths:
      - 'chord_metadata_service/mohpackets/schemas/**'
      - 'chord_metadata_service/mohpackets/models.py'

    
jobs:
  generate-moh-schema:
    name: Update MoH schema
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.head_ref }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install -r requirements/base.txt

      - name: Generate new schema.json
        run: |
          export DJANGO_SETTINGS_MODULE=config.settings.base
          python manage.py export_openapi_schema --api chord_metadata_service.mohpackets.apis.core.api | python -m json.tool > chord_metadata_service/mohpackets/docs/schema.json
      
      - name: Commit new schema.json
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: Update schema.json

      - name: Update schema.json with new SHA
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          REPO_NAME=${{ github.repository }}
          SHA=${{ steps.auto-commit-action.outputs.commit_hash }}
          SCHEMA_PATH=chord_metadata_service/mohpackets/docs/schema.json
          sed -i 's|"description": "This is the RESTful API for the MoH Service."|"description": "This is the RESTful API for the MoH Service. Based on https://raw.githubusercontent.com/'"$REPO_NAME"'/'"$SHA"'/'"$SCHEMA_PATH"'"|' $SCHEMA_PATH

      - name: Install widdershins
        run: npm install -g widdershins

      - name: Convert schema to OpenAPI documentation
        run: |
          npx widdershins ./chord_metadata_service/mohpackets/docs/schema.json -o ./chord_metadata_service/mohpackets/docs/schema.md -u ./chord_metadata_service/mohpackets/docs/widdershins/templates/openapi3 -c true --omitHeader true
      
      - name: Install PyYAML
        run: pip install PyYAML

      - name: Convert schema.json to schema.yml
        run: python -c 'import json, yaml; json.load(open("chord_metadata_service/mohpackets/docs/schema.json")); print(yaml.dump(json.load(open("chord_metadata_service/mohpackets/docs/schema.json"))))' > chord_metadata_service/mohpackets/docs/schema.yml

      - name: Update schemas with SHA
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update schemas with SHA
